import { Feather } from "@expo/vector-icons";
import * as Clipboard from "expo-clipboard";
import React, { useState } from "react";
import {
  Alert,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { KeyboardAwareScrollView } from "react-native-keyboard-controller";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { Badge } from "@/components/Badge";
import { Button } from "@/components/Button";
import { Card } from "@/components/Card";
import { ModalShell } from "@/components/ModalShell";
import { TextField } from "@/components/TextField";
import { useApp } from "@/contexts/AppContext";
import { useColors } from "@/hooks/useColors";

export default function OperatorsScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const { chefs, addChef, removeChef, callChef, currentWorkSession } = useApp();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [lastCreated, setLastCreated] = useState<{
    name: string;
    email: string;
    password: string;
  } | null>(null);

  const submit = async () => {
    setError(null);
    if (!name.trim()) return setError("Name is required.");
    if (!email.trim() || !email.includes("@"))
      return setError("Please enter a valid email.");
    if (
      chefs.some(
        (c) => c.email.trim().toLowerCase() === email.trim().toLowerCase(),
      )
    )
      return setError("An operator with this email already exists.");

    const chef = await addChef(name, email);
    setLastCreated({ name: chef.name, email: chef.email, password: chef.password });
    setName("");
    setEmail("");
  };

  const copy = async (text: string) => {
    await Clipboard.setStringAsync(text);
    Alert.alert("Copied", "Password copied to clipboard.");
  };

  const webBottom = Platform.OS === "web" ? 34 : 0;

  return (
    <ModalShell
      title="Manage operators"
      subtitle="Add or remove team members. Passwords are auto-generated."
    >
      <KeyboardAwareScrollView
        bottomOffset={20}
        keyboardShouldPersistTaps="handled"
        contentContainerStyle={{
          padding: 18,
          paddingBottom: insets.bottom + webBottom + 24,
          gap: 14,
        }}
      >
        <Card>
          <Text
            style={{
              color: colors.foreground,
              fontFamily: "Inter_700Bold",
              fontSize: 15,
            }}
          >
            Add an operator
          </Text>
          <Text
            style={{
              color: colors.mutedForeground,
              fontFamily: "Inter_400Regular",
              fontSize: 12,
              marginTop: 4,
            }}
          >
            Password is generated by signup order — first operator gets 111111,
            second gets 222222, and so on.
          </Text>

          <View style={{ marginTop: 14, gap: 10 }}>
            <TextField
              label="Operator name"
              placeholder="e.g. Maya Lopez"
              value={name}
              onChangeText={setName}
              autoCapitalize="words"
            />
            <TextField
              label="Email"
              placeholder="operator@workshop.com"
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
              errorText={error ?? undefined}
            />
          </View>

          <Button
            label={`Create operator account (password: ${String(chefs.length + 1).repeat(6)})`}
            icon="user-plus"
            onPress={submit}
            fullWidth
            style={{ marginTop: 14 }}
          />
        </Card>

        {lastCreated ? (
          <Card
            style={{ backgroundColor: colors.accent, borderColor: colors.accent }}
          >
            <View
              style={{
                flexDirection: "row",
                gap: 10,
                alignItems: "flex-start",
              }}
            >
              <Feather name="check-circle" size={18} color={colors.accentForeground} />
              <View style={{ flex: 1 }}>
                <Text
                  style={{
                    color: colors.accentForeground,
                    fontFamily: "Inter_700Bold",
                    fontSize: 13,
                  }}
                >
                  Operator created — share these credentials
                </Text>
                <Text
                  style={{
                    color: colors.accentForeground,
                    fontFamily: "Inter_500Medium",
                    fontSize: 13,
                    marginTop: 6,
                  }}
                >
                  {lastCreated.name} · {lastCreated.email}
                </Text>
                <Pressable
                  onPress={() => copy(lastCreated.password)}
                  style={[
                    styles.passBox,
                    { backgroundColor: "rgba(255,255,255,0.6)" },
                  ]}
                >
                  <Text style={styles.passText}>{lastCreated.password}</Text>
                  <Feather
                    name="copy"
                    size={14}
                    color={colors.accentForeground}
                  />
                </Pressable>
              </View>
            </View>
          </Card>
        ) : null}

        <Card>
          <View
            style={{
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <Text
              style={{
                color: colors.foreground,
                fontFamily: "Inter_700Bold",
                fontSize: 15,
              }}
            >
              Team
            </Text>
            <Badge tone="primary" label={`${chefs.length} operators`} />
          </View>

          {chefs.length === 0 ? (
            <Text
              style={{
                color: colors.mutedForeground,
                fontSize: 13,
                marginTop: 12,
              }}
            >
              No operators yet.
            </Text>
          ) : (
            <View style={{ marginTop: 12, gap: 10 }}>
              {chefs.map((chef) => {
                const ws = currentWorkSession(chef.id);
                return (
                  <View
                    key={chef.id}
                    style={[
                      styles.row,
                      { borderColor: colors.border, borderRadius: colors.radius },
                    ]}
                  >
                    <View style={{ flex: 1 }}>
                      <View
                        style={{
                          flexDirection: "row",
                          alignItems: "center",
                          gap: 8,
                        }}
                      >
                        <Text
                          style={{
                            fontFamily: "Inter_700Bold",
                            color: colors.foreground,
                            fontSize: 14,
                          }}
                        >
                          {chef.name}
                        </Text>
                        <Badge
                          tone={ws ? "success" : "muted"}
                          label={ws ? "On shift" : "Off"}
                        />
                      </View>
                      <Text
                        style={{
                          fontFamily: "Inter_400Regular",
                          color: colors.mutedForeground,
                          fontSize: 12,
                          marginTop: 2,
                        }}
                      >
                        {chef.email}
                      </Text>
                      <Pressable
                        onPress={() => copy(chef.password)}
                        style={{
                          flexDirection: "row",
                          alignItems: "center",
                          gap: 6,
                          marginTop: 6,
                        }}
                      >
                        <Feather
                          name="key"
                          size={11}
                          color={colors.mutedForeground}
                        />
                        <Text
                          style={{
                            fontFamily: "Inter_600SemiBold",
                            color: colors.foreground,
                            fontSize: 12,
                            letterSpacing: 1,
                          }}
                        >
                          {chef.password}
                        </Text>
                        <Feather
                          name="copy"
                          size={11}
                          color={colors.mutedForeground}
                        />
                      </Pressable>
                    </View>
                    <View style={{ gap: 6 }}>
                      <Pressable
                        onPress={() => callChef(chef.id, chef.name)}
                        style={[
                          styles.actionBtn,
                          { backgroundColor: colors.primary },
                        ]}
                      >
                        <Feather
                          name="phone-call"
                          size={14}
                          color="white"
                        />
                      </Pressable>
                      <Pressable
                        onPress={() => {
                          Alert.alert(
                            "Remove operator?",
                            `${chef.name} will lose access immediately.`,
                            [
                              { text: "Cancel", style: "cancel" },
                              {
                                text: "Remove",
                                style: "destructive",
                                onPress: () => removeChef(chef.id),
                              },
                            ],
                          );
                        }}
                        style={[
                          styles.actionBtn,
                          { backgroundColor: "#fee2e2" },
                        ]}
                      >
                        <Feather
                          name="user-minus"
                          size={14}
                          color={colors.destructive}
                        />
                      </Pressable>
                    </View>
                  </View>
                );
              })}
            </View>
          )}
        </Card>
      </KeyboardAwareScrollView>
    </ModalShell>
  );
}

const styles = StyleSheet.create({
  row: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderWidth: 1,
  },
  actionBtn: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  passBox: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  passText: {
    fontFamily: "Inter_700Bold",
    fontSize: 18,
    letterSpacing: 4,
    color: "#4c1d95",
  },
});
